services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend:v5.27.1
    container_name: map-orders-osrm
    ports:
      - "5563:5000"
    volumes:
      - ./data:/data
    restart: unless-stopped
    command: >
      /bin/bash -lc '
        set -euo pipefail
        mkdir -p /data

        PBF_NAME=central-fed-district-latest.osm.pbf
        DOWNLOAD_URL=https://download.geofabrik.de/russia/central-fed-district-latest.osm.pbf
        MD5_URL=$$DOWNLOAD_URL.md5
        PROFILE=/opt/car.lua
        ALGORITHM=mld
        BASE_NAME=$${PBF_NAME%.pbf}

        # скачать, если нет или файл подозрительно мал (защита от HTML-ответа)
        need_download=0
        if [ ! -f /data/$$PBF_NAME ]; then
          need_download=1
        elif [ $$(stat -c%s /data/$$PBF_NAME 2>/dev/null || echo 0) -lt 10485760 ]; then
          echo "Existing file is too small; removing and re-downloading"
          rm -f /data/$$PBF_NAME
          need_download=1
        fi

        if [ $$need_download -eq 1 ]; then
          echo "Downloading OSM extract from $$DOWNLOAD_URL"
          if command -v curl >/dev/null 2>&1; then
            curl -fL -o /data/$$PBF_NAME "$$DOWNLOAD_URL"
            curl -fsSL "$$MD5_URL" -o /data/$$PBF_NAME.md5 || true
          elif command -v wget >/dev/null 2>&1; then
            wget -O /data/$$PBF_NAME "$$DOWNLOAD_URL"
            wget -O /data/$$PBF_NAME.md5 "$$MD5_URL" || true
          else
            apt-get update && apt-get install -y --no-install-recommends curl ca-certificates && rm -rf /var/lib/apt/lists/*
            curl -fL -o /data/$$PBF_NAME "$$DOWNLOAD_URL"
            curl -fsSL "$$MD5_URL" -o /data/$$PBF_NAME.md5 || true
          fi
        fi

        # верификация md5 (если md5 файл удалось скачать)
        if [ -f /data/$$PBF_NAME.md5 ]; then
          md5_expected=$$(awk "{print \\$1}" /data/$$PBF_NAME.md5)
          md5_actual=$$(md5sum /data/$$PBF_NAME | awk "{print \\$1}")
          if [ "$$md5_expected" != "" ] && [ "$$md5_actual" != "$$md5_expected" ]; then
            echo "MD5 mismatch for $$PBF_NAME (got $$md5_actual, expected $$md5_expected)" >&2
            rm -f /data/$$PBF_NAME
            exit 1
          fi
        fi

        if [ ! -f /data/$$BASE_NAME.osrm ]; then
          echo "Preparing OSRM files (extract/partition/customize)..."
          osrm-extract -p "$$PROFILE" /data/$$PBF_NAME
          osrm-partition /data/$$BASE_NAME.osrm
          osrm-customize /data/$$BASE_NAME.osrm
        fi

        echo "Starting OSRM routed service on port 5000 via algorithm $$ALGORITHM"
        exec osrm-routed --algorithm "$$ALGORITHM" /data/$$BASE_NAME.osrm
      '
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:5000/health || curl -fsS http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
